export const projectsMeta = [
  {
    num: "01",
    title: "VERTEX",
    kind: "Scroll-Driven Film · Concept",
    href: "https://vertex-three-pi.vercel.app/",
    image: "/images/vertex.jpg",
    caseStudy: true,
    tags: ["React 19", "TypeScript", "Tailwind", "Lenis", "Web Audio API"],
  },
  {
    num: "02",
    title: "NORDEN",
    kind: "E-commerce · Concept",
    href: "https://norden-lebedev-labs.vercel.app/",
    image: "/images/norden.png",
    caseStudy: true,
    tags: ["React", "Tailwind", "Framer Motion", "Vercel"],
  },
  {
    num: "03",
    title: "Atelier №7",
    kind: "Editorial Website · Concept",
    href: "https://atelier-7-lebedev-labs.vercel.app/",
    image: "/images/atelier.png",
    caseStudy: true,
    tags: ["React", "Vite", "Tailwind", "Framer Motion"],
  },
  {
    num: "04",
    title: "Aquascape",
    kind: "Competition Platform",
    href: "https://aquascape.in.ua/en/2025",
    image: "/images/aquascape.png",
    caseStudy: true,
    tags: ["React", "Node.js", "PostgreSQL"],
  },
  {
    num: "05",
    title: "Porsche Center Dnipro",
    kind: "Automotive Platform",
    href: "https://porschednipro.com.ua/",
    image: "/images/porsche.png",
    caseStudy: true,
    tags: ["React", "Node.js", "MySQL"],
  },
  {
    num: "06",
    title: "SENTRY",
    kind: "Security Platform · Concept",
    href: "https://sentry-lebedev-labs.vercel.app/",
    image: "/images/sentry.png",
    caseStudy: true,
    tags: ["React", "TypeScript", "Tailwind", "SVG Charts"],
  },
  {
    num: "07",
    title: "PVR Media Reviews",
    kind: "WooCommerce Plugin",
    href: "https://pv-reviews.site/",
    image: "/images/pvr-banner.jpg",
    caseStudy: true,
    tags: ["WordPress", "WooCommerce", "PHP", "JavaScript"],
  },
  {
    num: "08",
    title: "Extended Reviews",
    kind: "OpenCart Module",
    href: "https://extended-reviews.com/ex_reviews_v5_en.html",
    image: "/images/ex-reviews.png",
    caseStudy: false,
    metric: "800+ sales · 50+ customer reviews",
    tags: ["OpenCart", "PHP", "JavaScript", "SEO"],
  },
] as const;

export const caseStudiesMeta = [
  {
    project: "vertex",
    href: "https://vertex-three-pi.vercel.app/",
    image: "/images/vertex-2.jpg",
    builtWith: "React 19 · Vite 6 · TypeScript · Tailwind CSS 3.4 · Lenis · HTML5 Video scrubbing · Web Audio API · FFmpeg · Vercel",
  },
  {
    project: "norden",
    href: "https://norden-lebedev-labs.vercel.app/",
    image: "/images/norden-2.png",
    builtWith: "React 19 · Vite · TypeScript · Tailwind CSS 4 · Framer Motion · React Router · Vercel",
  },
  {
    project: "atelier",
    href: "https://atelier-7-lebedev-labs.vercel.app/",
    image: "/images/atelier-2.png",
    builtWith: "React 19 · TypeScript · Vite · Tailwind CSS 4 · Framer Motion · React Router 7",
  },
  {
    project: "aquascape",
    href: "https://aquascape.in.ua/en/2025",
    image: "/images/aquascape-work.png",
    builtWith: "React · Node.js · Express · PostgreSQL · Docker",
  },
  {
    project: "porsche",
    href: "https://porschednipro.com.ua/",
    image: "/images/porsche.png",
    builtWith: "React · Node.js · MySQL",
  },
  {
    project: "sentry",
    href: "https://sentry-lebedev-labs.vercel.app/",
    image: "/images/sentry-2.png",
    builtWith: "React 19 · TypeScript · Vite · Tailwind CSS 4 · Custom SVG charts",
  },
  {
    project: "pvr",
    href: "https://pv-reviews.site/",
    image: "/images/pvr-banner.jpg",
    builtWith: "WordPress · WooCommerce · PHP · JavaScript",
  },
] as const;

export const labMeta = [
  { area: "Security", num: "01" },
  { area: "AI", num: "02" },
  { area: "Web", num: "03" },
] as const;

export const contactsMeta = [
  {
    label: "Email",
    value: "lebedev.labs@gmail.com",
    href: "mailto:lebedev.labs@gmail.com",
    icon: "mail",
  },
  { label: "Telegram", value: "@ExWebDev", href: "https://t.me/ExWebDev", icon: "send" },
  {
    label: "GitHub",
    value: "github.com/Lebedgor",
    href: "https://github.com/Lebedgor",
    icon: "github",
  },
  {
    label: "Upwork",
    value: "/freelancers/~01d1e42e…",
    href: "https://www.upwork.com/freelancers/~01d1e42e87a34b9d38",
    icon: "up",
  },
] as const;

export const skills = [
  "OpenCart",
  "WordPress",
  "WooCommerce",
  "Shopify",
  "PHP",
  "JavaScript",
  "React",
  "Node.js",
  "Express",
  "Prisma",
  "PostgreSQL",
  "MySQL",
  "REST APIs",
  "Docker",
  "SEO",
] as const;
